name: shop_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  envied: ^0.5.4+1
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
